sonar.projectKey=rohitkumarreddysakam_raptor
sonar.organization=rohitkumarreddysakam
sonar.sources=.
sonar.exclusions=**/tests/**,**/__pycache__/**,**/migrations/**,**/uploads/**,**/*.min.js,**/node_modules/**,**/*.db
sonar.python.version=3.11
